[project]
name = "SINGr"
version="0.0.1.dev2"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "seaborn",
    "inspice>=1.7.0.5",
    "ecdtools>=0.7.0",
    "pybis2spice",
    "scipy",
    "kmeans1d",
    "pandas",
    "Jinja2",
    "pydantic>=2.13.4",
]
authors = [
    {name = "Thomas Damjanovic"}
]
maintainers = [
    {name = "Thomas Damjanovic"}
]
readme = "README.md"
description = "ngSPICE Based Signal-Integrity Simulator and Analyser."

[build-system]
requires = ["uv", "uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "SINGr"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.mypy]
python_version = "3.14"

[tool.pyright]
reportOptionalSubscript = "information"
reportAssignmentType = "information"
reportArgumentType = "information"
reportGeneralTypeIssues = "information"
reportPossiblyUnboundVariable = "information"
reportCallIssue = "information"
reportReturnType = "information"
reportAttributeAccessIssue = "information"
reportOperatorIssue = "information"

[dependency-groups]
docs = [
    "autodoc-pydantic>=2.2.0",
    "markupsafe>=3.0.3",
    "shibuya>=2026.7.12",
    "sphinx>=8.1.3",
]
