[project]
name = "SINGr"
dynamic = ["version"]
dependencies = [
    "numpy",
    "seaborn",
    "InSpice"
]
maintainers = [
    {name = "Thomas Damjanovic"}
]
readme = "README.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path="pybis2spice/version.py"

[tool.mypy]
python_version = "3.14"

[project.optional-dependencies]
ibis = ["ecdtools", "pybis2spice"]

[tool.pyright]
reportOptionalSubscript = "information"
reportAssignmentType = "information"
reportArgumentType = "information"
reportGeneralTypeIssues = "information"
reportPossiblyUnboundVariable = "information"
reportCallIssue = "information"
reportReturnType = "information"
