[project]
name = "SINGr"
dynamic = ["version"]
dependencies = [
    "numpy",
    "seaborn",
    "InSpice",
    "ecdtools",
    "pybis2spice",
    "scipy",
    "kmeans1d",
    "pandas",
    "Jinja2"
]
maintainers = [
    {name = "Thomas Damjanovic"}
]
readme = "README.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path="src/SINGr/version.py"

[tool.mypy]
python_version = "3.14"

[tool.pyright]
reportOptionalSubscript = "information"
reportAssignmentType = "information"
reportArgumentType = "information"
reportGeneralTypeIssues = "information"
reportPossiblyUnboundVariable = "information"
reportCallIssue = "information"
reportReturnType = "information"
reportAttributeAccessIssue = "information"
reportOperatorIssue = "information"